export const quotes = [
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Let the beauty of what you love be what you do.", author: "Rumi" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "What you seek is seeking you.", author: "Rumi" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "I dwell in possibility.", author: "Emily Dickinson" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
    { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "I dwell in possibility.", author: "Emily Dickinson" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "We must let go of the life we have planned, so as to accept the one that is waiting for us.", author: "Joseph Campbell" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "What you seek is seeking you.", author: "Rumi" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "We must let go of the life we have planned, so as to accept the one that is waiting for us.", author: "Joseph Campbell" },
    { text: "Let the beauty of what you love be what you do.", author: "Rumi" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "What you seek is seeking you.", author: "Rumi" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" }
  ];
  

  